// Generated by IcedCoffeeScript 108.0.8
(function() {
  var COLORS, Monitors, addMonitor, alertMessage, getRandomColor, kaleido, renderMonitor, saveMonitors, syncMonitor, updateRenderedMonitor;

  window.kaleido = kaleido = {};

  Monitors = [];

  kaleido.init = function() {
    return $("#add-monitor-submit").click(function(e) {
      return addMonitor({
        name: $('#add-monitor-form-name').val(),
        url: $('#add-monitor-form-url').val(),
        selector: $('#add-monitor-form-selector').val()
      });
    });
  };

  addMonitor = function(monitor) {
    Monitors.push(monitor);
    renderMonitor(monitor);
    syncMonitor(monitor);
    saveMonitors();
    return alertMessage("Monitor Added Successfully!", 'success');
  };

  renderMonitor = function(monitor) {
    var HTMLstr, _ref;
    if (monitor.rendered) {
      return;
    } else {
      monitor.rendered = true;
    }
    HTMLstr = "<div id=\"monitor-" + monitor.name + "\">" + ((_ref = monitor.lastSync) != null ? _ref.result : void 0) + "</div>";
    return $(HTMLstr).appendTo($("#monitor-container"));
  };

  updateRenderedMonitor = function(monitor) {
    var _ref;
    return $("#monitor-" + monitor.name).text((_ref = monitor.lastSync) != null ? _ref.result : void 0);
  };

  syncMonitor = function(monitor, cb) {
    return $.get(monitor.url, function(data, status, xhr) {
      var $data;
      data = $(monitor.selector, data);
      data = monitor.process ? ($data = data, eval(monitor.process)) : data.text();
      monitor.lastSync = {
        time: _.now(),
        result: data
      };
      updateRenderedMonitor(monitor);
      console.log(JSON.stringify(data));
      return typeof cb === "function" ? cb() : void 0;
    });
  };

  saveMonitors = function(cb) {
    var MonitorsToSave;
    if (cb == null) {
      cb = _.identity;
    }
    MonitorsToSave = Monitors.map(function(monitor) {
      var _ref, _ref1;
      return {
        name: monitor.name,
        url: monitor.url,
        selector: monitor.selector,
        lastSync: {
          time: (_ref = monitor.lastSync) != null ? _ref.time : void 0,
          result: (_ref1 = monitor.lastSync) != null ? _ref1.result : void 0
        }
      };
    });
    return Windows.Storage.ApplicationData.current.roamingFolder.createFileAsync("Monitors.json", Windows.Storage.CreationCollisionOption.replaceExistring).then(function(file) {
      return Windows.Storage.FileIO.writeTextAsync(file, JSON.stringify(MonitorsToSave));
    }).done(cb);
  };

  alertMessage = function(msg, type) {
    var HTMLstr;
    if (type == null) {
      type = "info";
    }
    HTMLstr = "<div id=\"alerter\" class=\"alert alert-dismissible alert-" + type + "\" role=\"alert\">\n    <button type=\"button\" class=\"close\" data-dismiss=\"alert\"><span>&times;</span></button>\n    <span id=\"alerter-message\">" + msg + "</span>\n</div>";
    return $(HTMLstr).appendTo($('#alerter'));
  };

  COLORS = ["AliceBlue", "AntiqueWhite", "Aqua", "Aquamarine", "Azure", "Beige", "Bisque", "Black", "BlanchedAlmond", "Blue", "BlueViolet", "Brown", "BurlyWood", "CadetBlue", "Chartreuse", "Chocolate", "Coral", "CornflowerBlue", "Cornsilk", "Crimson", "Cyan", "DarkBlue", "DarkCyan", "DarkGoldenRod", "DarkGray", "DarkGreen", "DarkKhaki", "DarkMagenta", "DarkOliveGreen", "DarkOrange", "DarkOrchid", "DarkRed", "DarkSalmon", "DarkSeaGreen", "DarkSlateBlue", "DarkSlateGray", "DarkTurquoise", "DarkViolet", "DeepPink", "DeepSkyBlue", "DimGray", "DodgerBlue", "FireBrick", "FloralWhite", "ForestGreen", "Fuchsia", "Gainsboro", "GhostWhite", "Gold", "GoldenRod", "Gray", "Green", "GreenYellow", "HoneyDew", "HotPink", "IndianRed ", "Indigo  ", "Ivory", "Khaki", "Lavender", "LavenderBlush", "LawnGreen", "LemonChiffon", "LightBlue", "LightCoral", "LightCyan", "LightGoldenRodYellow", "LightGray", "LightGreen", "LightPink", "LightSalmon", "LightSeaGreen", "LightSkyBlue", "LightSlateGray", "LightSteelBlue", "LightYellow", "Lime", "LimeGreen", "Linen", "Magenta", "Maroon", "MediumAquaMarine", "MediumBlue", "MediumOrchid", "MediumPurple", "MediumSeaGreen", "MediumSlateBlue", "MediumSpringGreen", "MediumTurquoise", "MediumVioletRed", "MidnightBlue", "MintCream", "MistyRose", "Moccasin", "NavajoWhite", "Navy", "OldLace", "Olive", "OliveDrab", "Orange", "OrangeRed", "Orchid", "PaleGoldenRod", "PaleGreen", "PaleTurquoise", "PaleVioletRed", "PapayaWhip", "PeachPuff", "Peru", "Pink", "Plum", "PowderBlue", "Purple", "RebeccaPurple", "Red", "RosyBrown", "RoyalBlue", "SaddleBrown", "Salmon", "SandyBrown", "SeaGreen", "SeaShell", "Sienna", "Silver", "SkyBlue", "SlateBlue", "SlateGray", "Snow", "SpringGreen", "SteelBlue", "Tan", "Teal", "Thistle", "Tomato", "Turquoise", "Violet", "Wheat", "White", "WhiteSmoke", "Yellow", "YellowGreen"];

  getRandomColor = function() {
    return _.sample(COLORS);
  };

}).call(this);
